### ISSUE TITLE
Context Generator | FIWARE context URL does not work

### ISSUE THREAD

**Issue by a39172** [FIWARE/tutorials.Understanding-At-Context#10]
# Possible issue
I think that the context URL associated with FIWARE - `context.fiware = 'https://uri.fiware.org/ns/data-models#';` - in the file `context-file-generator/bin/jsonld.js` is outdated because it doesn't work.

## Related question
Let me take this opportunity to ask this question: suppose I have a "Company" entity defined as follows in my OpenAPI specification:
```
Company:
      type: object
      allOf:
        - $ref: "https://smart-data-models.github.io/dataModel.Organization/Organization/model.yaml#/Organization"
        - $ref: "https://smart-data-models.github.io/data-models/schema.org.yaml#/ContactPoint"
```

In the context file generated with the above generator I end up with the following definition: ` "Company": "fiware:Company"`. In this case should I change the definition to ` "Company": "fiware:Organization"` considering that the base model is called "Organization"?
