### ISSUE TITLE
Incorrect generation of @Context-File if prefixes are used in variable names

### ISSUE THREAD

**Issue by IngMiad** [FIWARE/tutorials.Understanding-At-Context#11]
Hello,

## Summary
I followed this tutorial and used the context-file-generator to generate our custom @Context-File. Unfortunately the context-file-generator seems to generate wrong @Context-files that produce errors in production. 

## Steps to reproduce
I have generated the data model according to the instructions from https://github.com/FIWARE/tutorials.Understanding-At-Context:
1. First I generated a model.yaml file. I don't want to share our whole model file in github (please ping me if I should provide it for you for testing-purposes), but I give you an example for problematic entities:
  ```
    ###############################
    ## CompressedAirDistribution ##
    ###############################
    CompressedAirDistribution:
      description: "Process management system function 'Compressed air distribution' with KKS function code: 'QFB' (de: 'Druckluftverteilung')"
      required:
        - "id"
        - "type"
        - "dateObserved"
        - "isSubsystemOf"
      properties:
        id:
          anyOf:
            - description: "Property. Identifier format of any NGSI entity"
              maxLength: 256
              minLength: 1
              pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
              type: "string"
            - description: "Property. Identifier format of any NGSI entity"
              format: "uri"
              type: "string"
          description: "Unique identifier of the entity"
          x-ngsi:
            type: "Property"
        type:
          description: "NGSI Entity type. It has to be 'CompressedAirDistribution' (a specific PCS part)"
          enum:
            - "CompressedAirDistribution"
          type: "string"
          x-ngsi:
            type: "Property"
        dateObserved:
          description: "Date of the observed entity defined by the user."
          type: "string"
          x-ngsi:
            type: "Property"
        isSubsystemOf:
          description: "This component is a sub component of another system"
          type: "string"
          x-ngsi:
            model: "https://schema.org/URL"
            type: "Relationship"
        kksFunction:
          description: "KKS function of property (level 1)"
          type: "string"
          x-ngsi:
            type: "Property"
        0QFB15CP001:Dr_DrLuAnl:U_AH:
          description: "Compressed air distribution Nr. 15 Measuring circuit Pressure Nr. 001  (HL alarm)"
          type: "boolean"
          x-ngsi:
            model: "https://schema.org/Boolean"
            type: "Property"
        0QFB15CP001:Dr_DrLuAnl:U_WL:
          description: "Compressed air distribution Nr. 15 Measuring circuit Pressure Nr. 001  (LL warning)"
          type: "boolean"
          x-ngsi:
            model: "https://schema.org/Boolean"
            type: "Property"
        0QFB15CP001:Dr_DrLuAnl:U_AL:
          description: "Compressed air distribution Nr. 15 Measuring circuit Pressure Nr. 001  (LL alarm)"
          type: "boolean"
          x-ngsi:
            model: "https://schema.org/Boolean"
            type: "Property"
        0QFB15CP001:Dr_DrLuAnl:U_WH:
          description: "Compressed air distribution Nr. 15 Measuring circuit Pressure Nr. 001  (HL warning)"
          type: "boolean"
          x-ngsi:
            model: "https://schema.org/Boolean"
            type: "Property"
        0QFB15CP001:Dr_DrLuAnl:U:
          description: "Compressed air distribution Nr. 15 Measuring circuit Pressure Nr. 001  (Analog value measurement)"
          type: "number"
          x-ngsi:
            model: "https://schema.org/Number"
            type: "Property"
  ```
3. then I checked its validity in Swagger-UI which has no issues
  
![grafik](https://github.com/FIWARE/tutorials.Understanding-At-Context/assets/7457382/8bfb5814-4152-40e8-982d-a75c298f22e2)

4. afterwards I used the Smart Data Model Tool to generate a @Context file (see datamodels.context-ngsild.jsonld and datamodels.md)
  
![grafik](https://github.com/FIWARE/tutorials.Understanding-At-Context/assets/7457382/9b56beda-26e7-4a67-80af-d52e43521b91)

## Issue
Swagger and the tool say that the provided API is valid and successfully generate the @context-file. I can also work with the generated file using IoT-Agent for OPC UA, Orion-LD and halfway also Mintaka - Mintaka is successfully writing entities based on provided @Context file, but it doesn't allow to use temporal interface based on that file. I discussed the issue in another issue with Mintaka developers: https://github.com/FIWARE/mintaka/issues/167

According to @wistefan the reason why Mintaka declines the provided @context-file in read-requests is that the @context-file has been generated incorrectly. In case ":" are used, these prefixes also need to be declared in @context file. As an example 
* This is the wrong @context produced by context-file-generator
  ```
  {
      "@context": {
          "type": "@type",
          "id": "@id",
          "ngsi-ld": "https://uri.etsi.org/ngsi-ld/",
          "fiware": "[https://uri.fiware.org/ns/data-models#](https://uri.fiware.org/ns/data-models)",
          "schema": "https://schema.org/",
          "0BLE10CS002:Drehzahl_DT:U": "fiware:0BLE10CS002:Drehzahl_DT:U"
      }
  }
  ```
* This would be the correct @context file with defined prefixes
  ```
  {
      "@context": {
          "type": "@type",
          "id": "@id",
          "ngsi-ld": "https://uri.etsi.org/ngsi-ld/",
          "fiware": "[https://uri.fiware.org/ns/data-models#](https://uri.fiware.org/ns/data-models)",
          "schema": "https://schema.org/",
          "0BLE10CS002" : "https://dlr.org/",
          "0BLE10CS002:Drehzahl_DT:U": {
            "@type":"fiware:0BLE10CS002:Drehzahl_DT:U"
        }
      }
  }
  ```

## Expectations
From my understanding the variable names I defined are according to NGSI-LD standard:
![grafik](https://github.com/FIWARE/tutorials.Understanding-At-Context/assets/7457382/be4cb62e-9861-4f82-8d7a-e765a3cfb04f)

So I would expect the context-file-generator to either throw an error if the variable names are not allowed (instead of claiming that API is valid) or generate the @context-file correctly. 

It is also not expected that only Mintaka recognizes the wrong context-file in read-requests, but not in write-requests. Orion-LD and IoT-Agent for OPC UA don't seem to recognize wrong @context-file at all.
